site_name: lean-ai-detector
site_url: https://norsulabs.github.io/lean-ai-detector/
nav: 
    - Home: index.md
    - About: about.md
    - Contact: contact.md
    - GitHub: https://github.com/norsulabs/lean-ai-detector/

theme: material

plugins: 
    - mkdocstrings